apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-db
spec:
  selector:
    matchLabels:
      app: echo-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: echo-db
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: devpass
            - name: MYSQL_DATABASE
              value: echo
            - name: MYSQL_USER
              value: devuser
            - name: MYSQL_PASSWORD
              value: devpass
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: echo-db
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: echo-db
